CREATE TABLE `t_publish_message` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`topic` VARCHAR(20) NOT NULL COMMENT '消息topic',
	`pub_key` VARCHAR(30) NOT NULL COMMENT '消息key',
	`tag` VARCHAR(10) NOT NULL COMMENT '消息tag',
	`body` VARCHAR(100) NOT NULL COMMENT '消息body',
	`pub_group` VARCHAR(25) NULL DEFAULT NULL COMMENT '生产者组',
	`stage` TINYINT(2) NULL DEFAULT NULL COMMENT '阶段（21.prepare 22.commit 23.rollback）',
	`cts` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	`uts` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=9
;